from flask import Flask

session = {'user':{'legal_data':{},
                   'name':'',
                   'adress':'',
                   'base_activity':'food',
                   'fin_data':{},
                   'coordinates':[],
                   'special_data':{}},
           'type_obj':{
                        'builts': ['Плотность застройки', False],
                        'metro_exits': ['Выходы метро', False],
                        'paid_parking': ['Платные парковки', False],
                        'closed_paid_parking': ['Закрытые парковки', False],
                        'cinemas': ['Кинотеатры', False],
                        'concert_halls': ['Концертные залы', False],
                        'theaters': ['Театры', False],
                        'museums': ['Музеи', False],
                        'circus': ['Цирки', False],
                        'food': ['Рестораны', False],
                        'data_wifi': ['Точки Wi-Fi', False],
                        'activity_peaple': ['Пешеходня активность', False],
                        'popular_place': ['Популярность места', False],
                        'atelier': ['Ателье', False],
                        'bathing_services': ['Бани', False],
                        'comprehensive_domestic_services': ['Дома быта', False],
                        'dry_cleanings_dyeing': ['Химчистки', False],
                        'education': ['Образование', False],
                        #'furniture_services': ['Ремонт мебели', False],
                        'hairdressers': ['Парикмахерские', False],
                        'home_electronics_services': ['Ремонт электроники', False],
                        #'intercepting_parking': ['Внутренние парковки', False],
                        #'jewelry_services': ['Ювелиры', False],
                        #'laundries': ['Прачечные', False],
                        #'metal_services': ['Ремонт металлоизделий', False],
                        #'other_domestic_services': ['Разные мастерские', False],
                        #'parks': ['Парки', False],
                        'pawnshops': ['Ломбарды', False],
                        'photo_studios': ['Фотостудии', False],
                        #'rental_services': ['Прокат', False],
                        #'ritual_services': ['Ритуальные улуги', False],
                        'saunas': ['Сауны', False],
                        #'self_service_dry_cleaners': ['Прачечные самообслуживания', False],
                        #'self_service_laundries': ['Прачечные самообслуживания', False],
                        'shoe_services': ['Ремонт обуви', False],
                        'watch_services': ['Ремонт часов', False]}
           }

app = Flask(__name__)

